### ISSUE TITLE
struct.error: unpack requires a string argument of length 8

### ISSUE THREAD

**Issue by LTsCreed** [BigNerd95/RouterOS-Backup-Tools#1]
hi,
can you help me with this error?
thanks

** Decrypt Backup **
Traceback (most recent call last):
  File "ROSbackup.py", line 207, in <module>
    main()
  File "ROSbackup.py", line 202, in main
    decrypt(args.input, args.output, args.password)
  File "ROSbackup.py", line 117, in decrypt
    magic, length = get_header(input_file)
  File "ROSbackup.py", line 24, in get_header
    header = unpack('<II', data)
struct.error: unpack requires a string argument of length 8

**Comment by BigNerd95** [comment]
Did you try running:

python3 ROSbackup.py ...
?

**Comment by LTsCreed** [comment]
python ROSbackup.py

./ROSb.. or python3 ROS.. gives me error
Traceback (most recent call last):
  File "ROSbackup.py", line 9, in <module>
    from Crypto.Cipher import ARC4
ImportError: No module named 'Crypto'

**Comment by BigNerd95** [comment]
So now the error is different
It seems that you have not installed the Crypto module

**Comment by BigNerd95** [comment]
To install it:
pip3 install pycrypto
