### ISSUE TITLE
Doesn't work on routerSO7

### ISSUE THREAD

**Issue by ilium007** [BigNerd95/RouterOS-Backup-Tools#15]
```
python ../RouterOS-Backup-Tools/ROSbackup.py decrypt -i backups/xxxxx_2020-11-27.backup -o backups/xxxxx_2020-11-27_clear.backup -p xxxxx

** Decrypt Backup **
Invalid file!
Cannot decrypt!
```

**Comment by ilium007** [comment]
python ../RouterOS-Backup-Tools/ROSbackup.py info -i backups/xxxxx_2020-11-27.backup
** Backup Info **
Invalid file!

**Comment by kaihendry** [comment]
Same issue here...

**Comment by m-emelchenkov** [comment]
Also can't unpack non-encrypted backup:
```
** Unpack Backup **
RouterOS Plaintext Backup
Length: 73660 bytes
Extracting backup...
Traceback (most recent call last):
  File "./ROSbackup.py", line 426, in <module>
    main()
  File "./ROSbackup.py", line 419, in main
    unpack(args.input, args.directory)
  File "./ROSbackup.py", line 292, in unpack
    files_num = unpack_files(input_file, length, unpack_directory)
  File "./ROSbackup.py", line 141, in unpack_files
    name = extract_data(input_file).decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xac in position 1: ordinal not in range(128)
```

**Comment by BigNerd95** [comment]
Newer version or RouterOS aren't supported yet
I have no time to extend the support at the moment
Sorry

**Comment by BigNerd95** [comment]
> Also can't unpack non-encrypted backup:
> 
> ```
> ** Unpack Backup **
> RouterOS Plaintext Backup
> Length: 73660 bytes
> Extracting backup...
> Traceback (most recent call last):
>   File "./ROSbackup.py", line 426, in <module>
>     main()
>   File "./ROSbackup.py", line 419, in main
>     unpack(args.input, args.directory)
>   File "./ROSbackup.py", line 292, in unpack
>     files_num = unpack_files(input_file, length, unpack_directory)
>   File "./ROSbackup.py", line 141, in unpack_files
>     name = extract_data(input_file).decode('ascii')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xac in position 1: ordinal not in range(128)
> ```

Just tested with a plaintext backup on version v6.47.8 (stable)
It is unpacked correctly for me
Are you using py2?

**Comment by m-emelchenkov** [comment]
> Just tested with a plaintext backup on version v6.47.8 (stable)
> It is unpacked correctly for me
> Are you using py2?

I meant it can't unpack unencrypted ROS 7 (related to issue subject), not ROS 6.
