### ISSUE TITLE
How to read the idx and dat file?

### ISSUE THREAD

**Issue by blackstrip** [BigNerd95/RouterOS-Backup-Tools#2]
Hi Guys,

How can i read and modify the idx and dat file? or some python module can do it?

**Comment by BigNerd95** [comment]
Try with some of these tools
https://github.com/0ki/mikrotik-tools?files=1

**Comment by blackstrip** [comment]
Thanks a lot. 
RouterOS-Backup-Tools is great work.

**Comment by BigNerd95** [comment]
Thank you very much!
I'll update this project as soon as I'll finish the reverse engineering of dat files

**Comment by blackstrip** [comment]
Cool, i'm in watching now.

**Comment by esstein** [comment]
> Try with some of these tools https://github.com/0ki/mikrotik-tools?files=1

Which command I have to use to decode dat files?

**Comment by KEMBL** [comment]
@esstein 
you need to take *.idx and *.dat files you want to decode and rename them as group.idx and group.dat. After, put them into the same folder with mt_dat_decoder.py and start:

python2 mt_dat_decoder.py > decoded.txt

inside decoded.txt will be decoded content though it is not too readable :)
More information: https://forum.mikrotik.com/viewtopic.php?t=186036#p976367
