### ISSUE TITLE
RouterOS v 6.44

### ISSUE THREAD

**Issue by royaldunlin** [BigNerd95/RouterOS-Backup-Tools#7]
The program reports "Invalid file!" with backups from RouterOS v 6.44.

**Comment by BigNerd95** [comment]
Maybe it is encrypted with AES128-CTR
My tool doesn't support this format yet

**Comment by oryanperl** [comment]
> this

is it okay if i go ahead and add support to this method and simply open a pull request for you?

**Comment by BigNerd95** [comment]
```is it okay if i go ahead and add support to this method and simply open a pull request for you?``` 
sure!
