### ISSUE TITLE
issue in decrypting

### ISSUE THREAD

**Issue by barmoudeh** [BigNerd95/RouterOS-Backup-Tools#8]
hello I get this error:
RouterOS Encrypted Backup
('Length:', 130590, 'bytes')
Traceback (most recent call last):
  File "ROSbackup.py", line 426, in <module>
    main()
  File "ROSbackup.py", line 415, in main
    decrypt(args.input, args.output, args.password)
  File "ROSbackup.py", line 225, in decrypt
    print("Salt (hex):", salt.hex())
AttributeError: 'str' object has no attribute 'hex'

**Comment by BigNerd95** [comment]
Did you use python2?

**Comment by lamasek** [comment]
Hello, I have similar issue - deciphering config with aes-sha256 did not working:
  ROSbackup.py decrypt -i domgw.netio.eu-20191108-1612.backup -o domgw.netio.eu- 20191108-1612.plain -p bezhesla
  ** Decrypt Backup **
  Invalid file!
  Cannot decrypt!

When I use RC4 it works perfectly, so thanks for your software, it is working at least like this...

**Comment by BigNerd95** [comment]
My tool doesn't support AES yet
I'll add it as soon as I have time
